---
title: "Zukunftstag_svg"
author: "Lilith"
date: "2024-10-24"
output: html_document
---

```{r setup, include=FALSE}
library(magick)
library(rsvg)
```


Bilder einlesen
```{r einlesen}
# Organismen
fungus_blau <- image_read_svg("../pictures/241114_Zukunftstag_Fungus_Gross_Blau-01.svg", width = 350)
fungus_rot <- image_read_svg("../pictures/241114_Zukunftstag_Fungus_Gross_Rot-01.svg", width = 350)
fungus_weiss <- image_read_svg("../pictures/241114_Zukunftstag_Fungus_Gross_Weiss-01.svg", width = 350)
fungus_gelb <- image_read_svg("../pictures/241114_Zukunftstag_Fungus_Gross_Gelb-01.svg", width = 350)
bakterium_rot <- image_read_svg("../pictures/bacteria-svgrepo-com.svg", width = 250)
bakterium_grün <- image_read_svg("../pictures/microbe-svgrepo-com.svg", width = 350)
bakterium_grün_rot <- image_read_svg("../pictures/bacteria-5.svg", width = 350)
bakterium_blau <- image_read_svg("../pictures/bacteria_blue.svg", width = 350)
bakterium_weiss <- image_read_svg("../pictures/bacteria_white.svg", width = 350)


# Umgebungen
blatt <- image_read_svg("../pictures/leaf-svgrepo-com.svg", width = 350)
hand_1 <- image_read_svg("../pictures/hand-with-fingers-splayed-skin-1-svgrepo-com.svg", width = 600)
hand_2 <- image_read_svg("../pictures/hand-with-fingers-splayed-skin-2-svgrepo-com.svg", width = 600)
hand_3 <- image_read_svg("../pictures/hand-with-fingers-splayed-skin-3-svgrepo-com.svg", width = 600)
hand_4 <- image_read_svg("../pictures/hand-with-fingers-splayed-skin-4-svgrepo-com.svg", width = 600)
hand_5 <- image_read_svg("../pictures/hand-with-fingers-splayed-skin-5-svgrepo-com.svg", width = 600)
erde <- image_read_svg("../pictures/misc-proto-dirt-pile.svg", width = 1000)
wasser <- image_read_svg("../pictures/water-drop-svgrepo-com.svg", width = 350)

# Lupen
lupe_1 <- image_read_svg("../pictures/magnifying-glass-9-svgrepo-com.svg", width = 350)
lupe_2 <- image_read_svg("../pictures/magnifying-glass-search-svgrepo-com.svg", width = 350)
```


Wähle deine Organismen, Umgebung, Hintergrundsfarbe und Lupe
```{r meine Wahl}
mein_name = ""
organismus_1 = bakterium_blau
organismus_2 = fungus_weiss
hintergrund_farbe = "lightblue"
umgebung = blatt
lupe = lupe_1
```


Hintergrundfarbe
```{r hintergrundfarbe, echo=FALSE}
# Hintergrundfarbe
hintergrund <- image_blank(width = 1000, height = 1000, color = hintergrund_farbe)
print(hintergrund)
```

Umgebung auf Hintergrund
```{r Umgebung auf Hintergrund, echo=FALSE}
# Organismus mit Umgebung auf den Hintergrund hinzufügen
umgebung_hintergrund <- image_composite(hintergrund, image_scale(umgebung, "x500"), offset = "+100+100")
print(umgebung_hintergrund)
```

erster Organismus auf Umgebung hinzufügen
```{r erster Organismus mit Umgebung kombinieren, echo=FALSE}
# Organismus drehen
organismus_schräg <- image_scale(image_rotate(image_background(organismus_1, "none"), 0), "x100")
# Organismus mit Umgebung kombinieren
organismus_umgebung <- image_composite(umgebung_hintergrund, organismus_schräg, offset = "+350+350")
print(organismus_umgebung)
```

zweiter Organismus auf den Hintergrund hinzufügen
```{r zweiter Organismus auf den Hintergrund hinzufügen, echo=FALSE}
organismus_schräg_2 <- image_scale(image_rotate(image_background(organismus_2, "none"), 0), "x100")
# weiterer Organismus
organismen_umgebung <- image_composite(organismus_umgebung, organismus_schräg_2, offset = "+250+200")
print(organismen_umgebung)
```

Lupe hinzufügen
```{r Lupe hinzufügen, echo=FALSE}
# Lupe auf das Bild hinzufügen
lupe_organismus_umgebung_hintergrund <- image_composite(organismen_umgebung, image_scale(lupe, "x600"), offset = "+135+135")
# Bild anzeigen
print(lupe_organismus_umgebung_hintergrund)
```

Bild speichern
```{r Bild speichern, echo=FALSE}
image_write(lupe_organismus_umgebung_hintergrund, path = paste0("../", mein_name, "_bild.png"), format = "png")
```
